name: moody
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_storage: ^3.0.6
  cloud_firestore: ^0.12.9+4
  mlkit: ^0.14.1
  image_picker: ^0.6.1+4
  flutter_icons: ^0.3.1
  radial_button: ^0.1.4
  carousel_slider: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: QuicksandB
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
    - family: QuicksandL
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf

