name: moody
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_storage: ^3.0.6
  image_picker: ^0.6.1+8
  flutter_icons: ^0.3.1
  radial_button: ^0.1.4
  nice_button: ^0.1.7
  gradient_widgets: ^0.5.0
  flutter_youtube: ^2.0.0
  introduction_screen: ^1.0.6
  meta: ^1.1.7
  mlkit:
    git:
      url: git://github.com/azihsoyn/flutter_mlkit.git
      ref: feature/for_ios_breaking_change


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: QuicksandB
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
    - family: QuicksandL
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf

  assets:
    - assets/images/arrow1.png
    - assets/images/2.0x/arrow1@2x.png
    - assets/images/3.0x/arrow1@3x.png
    - assets/images/pic1.jpg
    - assets/images/pic2.jpg
    - assets/images/pic3.jpg
    - assets/images/pic4.jpg
    - assets/images/yellow.png
    - assets/images/video.png
    - assets/images/smilePink.png
    - assets/images/buttons.png

